"""Curated pedagogical script templates for 30-second explainer videos with LaTeX formulas."""

from typing import Dict

from app.models.script import Scene, SupportedTopic, VideoScript

TEMPLATES: Dict[SupportedTopic, VideoScript] = {
    SupportedTopic.PH_SCALE: VideoScript(
        topic=SupportedTopic.PH_SCALE,
        title="How the pH Scale Works: Acids, Bases, and Hydrogen Ions",
        overview="A complete 30-second visual explanation of the logarithmic pH scale, hydrogen ions, and acid-base neutrality.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Universal Acidity Scale",
                narration="From tangy lemon juice to slippery household soap, solutions carry varying chemical powers. The pH scale provides a standardized measurement spectrum from zero all the way to fourteen.",
                visual_type="ph_spectrum",
                key_takeaway="The pH scale spans 0 to 14, measuring chemical acidity and alkalinity.",
                latex_formula=r"0 \le \mathrm{pH} \le 14",
                duration_target_seconds=7.0,
            ),
            Scene(
                scene_id=2,
                title="Hydrogen Ions and the Logarithmic Law",
                narration="At its heart, pH quantifies the exact concentration of active hydrogen ions in water. Mathematically, it is defined as the negative base ten logarithm of the hydrogen ion molarity.",
                visual_type="ph_equation",
                key_takeaway="pH is inversely proportional to hydrogen ion concentration on a log10 scale.",
                latex_formula=r"\mathrm{pH} = -\log_{10}[\mathrm{H}^+]",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Logarithmic Multipliers",
                narration="Because this relationship is logarithmic, each single step represents a ten-fold change. A solution at pH 5 is ten times more acidic than pH 6, and one hundred times more acidic than pure water at 7.",
                visual_type="ph_logarithmic",
                key_takeaway="Each step represents a 10x multiplier in hydrogen ion concentration.",
                latex_formula=r"[\mathrm{H}^+] = 10^{-\mathrm{pH}}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="The Equilibrium of Neutrality",
                narration="At pH seven, hydrogen and hydroxide ions balance in equal harmony. Values below seven reveal excess acidic protons, while values above indicate an abundance of alkaline hydroxide.",
                visual_type="ph_summary",
                key_takeaway="pH 7 is perfectly neutral, balancing H+ and OH- ions in water.",
                latex_formula=r"\mathrm{H}_2\mathrm{O} \rightleftharpoons \mathrm{H}^+ + \mathrm{OH}^-",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.COVALENT_BONDS: VideoScript(
        topic=SupportedTopic.COVALENT_BONDS,
        title="Why Atoms Form Covalent Bonds",
        overview="Discover how nonmetal atoms achieve electronic stability by sharing valence electron pairs.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Drive for Electronic Stability",
                narration="Atoms in nature are constantly driven toward thermodynamic stability. Most main group elements achieve their lowest energy state when their outer valence shell holds eight electrons.",
                visual_type="covalent_octet",
                key_takeaway="Atoms seek complete outer valence shells to achieve stable configurations.",
                latex_formula=r"s^2 p^6 \implies \text{Octet Stability}",
                duration_target_seconds=7.0,
            ),
            Scene(
                scene_id=2,
                title="Orbital Overlap and Electron Sharing",
                narration="When nonmetal atoms encounter one another, their high electronegativities prevent either from seizing electrons outright. Instead, their atomic orbitals merge, forming shared electron pairs.",
                visual_type="covalent_sharing",
                key_takeaway="Nonmetals share electron pairs rather than transferring them.",
                latex_formula=r"\mathrm{H}\cdot + \cdot\mathrm{H} \rightarrow \mathrm{H}:\mathrm{H}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Electrostatic Molecular Binding",
                narration="These shared negative electrons are pulled equally by the positive nuclei of both partner atoms. This mutual attraction produces a strong electrostatic bond that anchors the molecule together.",
                visual_type="covalent_molecule",
                key_takeaway="Simultaneous attraction of nuclei to shared electrons holds the bond tight.",
                latex_formula=r"F = \frac{k \cdot q_1 q_2}{r^2}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="The Architecture of Molecular Matter",
                narration="Through covalent sharing, essential life-giving molecules like water, methane, and DNA take form, creating stable molecular architectures that build our organic world.",
                visual_type="covalent_summary",
                key_takeaway="Covalent bonds build discrete, robust molecular structures.",
                latex_formula=r"2\mathrm{H}_2 + \mathrm{O}_2 \rightarrow 2\mathrm{H}_2\mathrm{O}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.IONIC_VS_COVALENT: VideoScript(
        topic=SupportedTopic.IONIC_VS_COVALENT,
        title="Ionic vs Covalent Bonding: The Essential Differences",
        overview="Compare electron transfer in ionic crystalline lattices against electron sharing in discrete covalent molecules.",
        scenes=[
            Scene(
                scene_id=1,
                title="Two Paths to Chemical Unity",
                narration="Chemical bonding comes down to one decisive question: do atoms transfer electrons completely, or do they share them mutually? This distinction separates ionic and covalent matter.",
                visual_type="bonding_overview",
                key_takeaway="Atoms bond through either electron transfer (ionic) or electron sharing (covalent).",
                latex_formula=r"\Delta\chi > 2.0 \implies \text{Ionic}, \quad \Delta\chi < 1.7 \implies \text{Covalent}",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Ionic Bonding: Complete Transfer",
                narration="In ionic bonds, an electropositive metal surrenders an electron to an electronegative nonmetal. Oppositely charged ions attract, packing tightly into a rigid, crystalline lattice.",
                visual_type="ionic_transfer",
                key_takeaway="Metals donate electrons to nonmetals, forming electrostatic ionic lattices.",
                latex_formula=r"\mathrm{Na} + \mathrm{Cl} \rightarrow \mathrm{Na}^+ + \mathrm{Cl}^-",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Covalent Bonding: Mutual Orbital Sharing",
                narration="In covalent bonds, nonmetal atoms share electron pairs between overlapping valence orbitals, constructing distinct, localized molecular units rather than continuous crystal networks.",
                visual_type="covalent_overlap",
                key_takeaway="Covalent bonds involve localized sharing of valence electron pairs.",
                latex_formula=r"\mathrm{H}_2\mathrm{O}, \quad \mathrm{CH}_4, \quad \mathrm{CO}_2",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Physical Properties in Contrast",
                narration="Because ionic bonds involve vast electrostatic grids, salts exhibit very high melting temperatures. Covalent molecules enjoy directional bonds, producing gases, liquids, and flexible plastics.",
                visual_type="comparison_table",
                key_takeaway="Ionic compounds are hard, high-melting crystals; covalent substances form diverse molecules.",
                latex_formula=r"T_{\mathrm{melt}}(\mathrm{NaCl}) = 801^{\circ}\mathrm{C} \gg T_{\mathrm{melt}}(\mathrm{H}_2\mathrm{O}) = 0^{\circ}\mathrm{C}",
                duration_target_seconds=8.0,
            ),
        ],
    ),
    SupportedTopic.ATOMIC_STRUCTURE: VideoScript(
        topic=SupportedTopic.ATOMIC_STRUCTURE,
        title="The Structure of the Atom and Subatomic Particles",
        overview="Explore the core architecture of the atom: the central nucleus of protons and neutrons surrounded by quantized electron shells.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Building Blocks of Matter",
                narration="Every element in the cosmos is constructed from tiny atomic building blocks. Though once thought indivisible, every atom contains three fundamental subatomic particles.",
                visual_type="atomic_intro",
                key_takeaway="Atoms consist of protons, neutrons, and electrons.",
                latex_formula=r"\text{Atom} = p^+ + n^0 + e^-",
                duration_target_seconds=7.0,
            ),
            Scene(
                scene_id=2,
                title="The Dense Central Nucleus",
                narration="At the center lies the ultra-dense atomic nucleus, containing positively charged protons and neutral neutrons, holding over ninety-nine point nine percent of the entire atomic mass.",
                visual_type="atomic_nucleus",
                key_takeaway="Protons and neutrons pack the central nucleus with positive charge.",
                latex_formula=r"m_{\text{nucleus}} \approx 99.9\% \cdot m_{\text{atom}}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Quantized Electron Shells",
                narration="Orbiting the nucleus in distinct energy levels are negatively charged electrons. Under the Bohr model, each shell accommodates a strictly limited capacity of two, eight, and eighteen electrons.",
                visual_type="atomic_shells",
                key_takeaway="Electrons inhabit quantized energy levels with maximum capacity 2n^2.",
                latex_formula=r"N_{\max} = 2n^2 \implies 2, 8, 18, 32",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Valence and Chemical Reactivity",
                narration="Electrons residing in the outermost valence shell dictate all chemical reactions. When valence shells are full, atoms remain unreactive; when incomplete, they bond to build the universe.",
                visual_type="atomic_summary",
                key_takeaway="Valence electrons govern chemical reactivity and molecular formation.",
                latex_formula=r"\text{Valence Shell} \implies \text{Chemical Behavior}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.EXO_VS_ENDOTHERMIC: VideoScript(
        topic=SupportedTopic.EXO_VS_ENDOTHERMIC,
        title="Exothermic vs Endothermic Reactions: Energy Flows in Chemistry",
        overview="Understand reaction coordinates, activation energy, and whether reactions release heat or absorb energy from their surroundings.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Thermodynamics of Reactions",
                narration="Chemical reactions constantly exchange heat with their environment. Some release intense thermal energy, while others absorb ambient heat, cooling their surroundings.",
                visual_type="energy_intro",
                key_takeaway="Chemical reactions either release heat (exothermic) or absorb heat (endothermic).",
                latex_formula=r"\Delta H = H_{\mathrm{products}} - H_{\mathrm{reactants}}",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Exothermic Reactions: Releasing Thermal Energy",
                narration="In exothermic reactions, such as combustion, chemical bonds in the products are stronger and more stable than the reactants. The excess energy is expelled as radiant heat and light.",
                visual_type="exothermic_profile",
                key_takeaway="Exothermic: Products have lower energy than reactants; Delta H is negative.",
                latex_formula=r"\Delta H < 0 \quad (\text{Heat Released})",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Endothermic Reactions: Absorbing Heat",
                narration="Conversely, endothermic reactions absorb heat from their surroundings to bridge the energy deficit. The products store greater chemical enthalpy than the original reactants.",
                visual_type="endothermic_profile",
                key_takeaway="Endothermic: Products have higher energy than reactants; Delta H is positive.",
                latex_formula=r"\Delta H > 0 \quad (\text{Heat Absorbed})",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="The Activation Energy Hill",
                narration="Both pathways require an initial input of activation energy to climb the transition barrier before breaking existing bonds and synthesizing new, enduring chemical structures.",
                visual_type="energy_summary",
                key_takeaway="Activation energy Ea is the kinetic threshold required to initiate reaction.",
                latex_formula=r"k = A \cdot e^{-\frac{E_a}{RT}}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.PERIODIC_TRENDS: VideoScript(
        topic=SupportedTopic.PERIODIC_TRENDS,
        title="How the Periodic Table Organizes Elements and Periodic Trends",
        overview="Explore atomic numbers, periods, groups, and the universal trends of electronegativity and atomic radius across the periodic table.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Map of the Elements",
                narration="The periodic table organizes all one hundred and eighteen known elements systematically by increasing atomic number, mapping out predictable chemical behaviors across periods and groups.",
                visual_type="periodic_intro",
                key_takeaway="Elements are organized by atomic number into periods (rows) and groups (columns).",
                latex_formula=r"Z = \text{Number of Protons}",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Electronegativity: The Pull for Electrons",
                narration="Electronegativity measures an atom's greedy pull for shared electrons. As you move left to right across a period, effective nuclear charge increases, pulling electrons with greater force.",
                visual_type="electronegativity_trend",
                key_takeaway="Electronegativity increases across periods and decreases down groups.",
                latex_formula=r"\chi_{\mathrm{F}} = 3.98 \quad (\text{Most Electronegative})",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Atomic Radius: The Size Gradient",
                narration="Atomic size follows an inverse trajectory. Atoms shrink across a period due to stronger nuclear pull, but expand down each group as brand new electron shells are added.",
                visual_type="atomic_radius_trend",
                key_takeaway="Atomic radius decreases left-to-right and increases top-to-bottom.",
                latex_formula=r"r_{\mathrm{atom}} \propto \frac{n^2}{Z_{\mathrm{eff}}}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Predicting Chemical Reactivity",
                narration="These periodic trends allow chemists to predict how any element will bond and react, making Mendeleev's periodic table the ultimate predictive guide in all of modern science.",
                visual_type="periodic_summary",
                key_takeaway="Periodic trends provide predictive power for all chemical interactions.",
                latex_formula=r"\text{Position on Table} \implies \text{Reactivity \& Bonding}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.STATES_OF_MATTER: VideoScript(
        topic=SupportedTopic.STATES_OF_MATTER,
        title="States of Matter and Phase Transitions",
        overview="Visualize particle kinetics across solids, liquids, and gases, and how thermal energy drives phase transformations.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Kinetic Nature of Matter",
                narration="All substances in our physical universe exist in distinct states of matter: solid, liquid, or gas, determined by the kinetic energy of their constituent molecules.",
                visual_type="matter_intro",
                key_takeaway="Matter exists as solid, liquid, or gas depending on molecular kinetic energy.",
                latex_formula=r"\overline{E_k} = \frac{3}{2} k_B T",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Solid Lattice to Fluid Liquid",
                narration="In a solid, atoms are held firmly in a rigid crystal lattice, merely vibrating in place. Supplying heat increases thermal vibrations until the lattice melts into a fluid, flowing liquid.",
                visual_type="solid_liquid_phase",
                key_takeaway="Adding heat breaks rigid crystal bonds, transitioning solids to liquids.",
                latex_formula=r"\mathrm{Solid} + \Delta H_{\mathrm{fusion}} \rightarrow \mathrm{Liquid}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Vaporization to High-Velocity Gas",
                narration="Adding even more heat energy allows molecules to completely overcome intermolecular attractions, escaping rapidly into the gas phase where particles freely collide at high velocities.",
                visual_type="liquid_gas_phase",
                key_takeaway="Vaporization frees molecules into high-speed, chaotic gas collisions.",
                latex_formula=r"\mathrm{Liquid} + \Delta H_{\mathrm{vap}} \rightarrow \mathrm{Gas}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Phase Equilibrium and Conservation",
                narration="Throughout every state change, molecular composition remains completely conserved. Temperature simply dictates whether forces of attraction or kinetic speeds govern the system.",
                visual_type="matter_summary",
                key_takeaway="Phase changes alter physical organization while chemical identity remains conserved.",
                latex_formula=r"\mathrm{H}_2\mathrm{O(s)} \rightleftharpoons \mathrm{H}_2\mathrm{O(l)} \rightleftharpoons \mathrm{H}_2\mathrm{O(g)}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.ACID_BASE_NEUTRALIZATION: VideoScript(
        topic=SupportedTopic.ACID_BASE_NEUTRALIZATION,
        title="Acid-Base Neutralization and Titration Reactions",
        overview="Explore what happens when acidic hydronium meets basic hydroxide to form neutral water and salt.",
        scenes=[
            Scene(
                scene_id=1,
                title="When Opposites Meet",
                narration="Acids and bases represent opposite extremes of chemical reactivity. When mixed in stoichiometric balance, their aggressive properties neutralize each other into harmless, stable products.",
                visual_type="neutralization_intro",
                key_takeaway="Neutralization occurs when acids and bases react to cancel each other out.",
                latex_formula=r"\mathrm{Acid} + \mathrm{Base} \rightarrow \mathrm{Salt} + \mathrm{Water}",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="The Fundamental Ionic Reaction",
                narration="At the microscopic level, acidic hydrogen ions and basic hydroxide ions combine rapidly to form pure, stable water molecules, eliminating free protons from the solution.",
                visual_type="neutralization_reaction",
                key_takeaway="Hydronium and hydroxide combine directly into water molecules.",
                latex_formula=r"\mathrm{H}^+ + \mathrm{OH}^- \rightarrow \mathrm{H}_2\mathrm{O}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Salt Formation and pH Shift",
                narration="Meanwhile, the spectator counter-ions combine into a dissolved mineral salt. The solution's pH shifts dramatically from strong acid or base toward neutral seven.",
                visual_type="neutralization_indicator",
                key_takeaway="Counter-ions form salt, while solution pH shifts toward neutral 7.",
                latex_formula=r"\mathrm{HCl} + \mathrm{NaOH} \rightarrow \mathrm{NaCl} + \mathrm{H}_2\mathrm{O}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Titration and Analytical Precision",
                narration="Chemists harness this reaction in titrations, using precise volumetric delivery and color indicators to measure the unknown concentration of acids and bases in medicine and industry.",
                visual_type="neutralization_summary",
                key_takeaway="Titration uses neutralization to accurately calculate chemical concentrations.",
                latex_formula=r"M_1 V_1 = M_2 V_2 \implies \text{Equivalence Point}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.OTHER_STEM: VideoScript(
        topic=SupportedTopic.OTHER_STEM,
        title="Exploring Science: Foundational Principles of Nature",
        overview="An educational exploration of core scientific principles governing physical and molecular interactions.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Framework of Physical Reality",
                narration="Scientific principles provide an empirical framework for deciphering natural systems, modeling the behavior of matter, energy, and fundamental forces across the universe.",
                visual_type="general_intro",
                key_takeaway="Observation and mathematical models describe natural behavior.",
                latex_formula=r"E = mc^2",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Thermodynamic Laws and Equilibrium",
                narration="Physical systems naturally evolve toward states of minimized free energy and maximum thermodynamic stability, dictating chemical spontaneity and reaction rates.",
                visual_type="general_mechanism",
                key_takeaway="Physical systems minimize potential energy to reach thermodynamic equilibrium.",
                latex_formula=r"\Delta G = \Delta H - T\Delta S < 0",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Scientific Application and Discovery",
                narration="Understanding these core laws empowers scientists to synthesize novel materials, discover life-saving pharmaceuticals, and engineer advanced technologies for humanity.",
                visual_type="general_summary",
                key_takeaway="Foundational scientific understanding drives innovation and modern technology.",
                latex_formula=r"\vec{F} = m\vec{a}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
}


def get_template_script(topic: SupportedTopic) -> VideoScript:
    """Retrieve the high-fidelity curated script for a topic."""
    return TEMPLATES.get(topic, TEMPLATES[SupportedTopic.OTHER_STEM])
