"""Curated pedagogical script templates for 30-second explainer videos with LaTeX formulas."""

from typing import Dict

from app.models.script import Scene, SupportedTopic, VideoScript

TEMPLATES: Dict[SupportedTopic, VideoScript] = {
    SupportedTopic.PH_SCALE: VideoScript(
        topic=SupportedTopic.PH_SCALE,
        title="How the pH Scale Works: Acids, Bases, and Hydrogen Ions",
        overview="A complete 30-second visual explanation of the logarithmic pH scale, hydrogen ions, and acid-base neutrality.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Universal Acidity Scale",
                narration="The pH scale measures how acidic or alkaline a chemical solution is, ranging from zero to fourteen.",
                visual_type="ph_spectrum",
                key_takeaway="The pH scale spans 0 to 14, measuring chemical acidity and alkalinity.",
                latex_formula=r"0 \le \mathrm{pH} \le 14",
                duration_target_seconds=7.0,
            ),
            Scene(
                scene_id=2,
                title="Hydrogen Ions and the Logarithmic Law",
                narration="It quantifies hydrogen ion concentration mathematically as the negative base ten logarithm of proton molarity.",
                visual_type="ph_equation",
                key_takeaway="pH is inversely proportional to hydrogen ion concentration on a log10 scale.",
                latex_formula=r"\mathrm{pH} = -\log_{10}[\mathrm{H}^+]",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Logarithmic Multipliers",
                narration="Because the scale is logarithmic, each single step represents a tenfold change in hydrogen ion concentration.",
                visual_type="ph_logarithmic",
                key_takeaway="Each step represents a 10x multiplier in hydrogen ion concentration.",
                latex_formula=r"[\mathrm{H}^+] = 10^{-\mathrm{pH}}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="The Equilibrium of Neutrality",
                narration="At pH seven, hydrogen and hydroxide balance equally. Lower values are acids, while higher values are bases.",
                visual_type="ph_summary",
                key_takeaway="pH 7 is perfectly neutral, balancing H+ and OH- ions in water.",
                latex_formula=r"\mathrm{H}_2\mathrm{O} \rightleftharpoons \mathrm{H}^+ + \mathrm{OH}^-",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.COVALENT_BONDS: VideoScript(
        topic=SupportedTopic.COVALENT_BONDS,
        title="Why Atoms Form Covalent Bonds",
        overview="Discover how nonmetal atoms achieve electronic stability by sharing valence electron pairs.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Drive for Electronic Stability",
                narration="Atoms in nature seek electronic stability, striving to achieve complete outer valence shells with eight electrons.",
                visual_type="covalent_octet",
                key_takeaway="Atoms seek complete outer valence shells to achieve stable configurations.",
                latex_formula=r"s^2 p^6 \implies \text{Octet Stability}",
                duration_target_seconds=7.0,
            ),
            Scene(
                scene_id=2,
                title="Orbital Overlap and Electron Sharing",
                narration="When nonmetal atoms encounter one another, their high electronegativity drives them to share valence electron pairs.",
                visual_type="covalent_sharing",
                key_takeaway="Nonmetals share electron pairs rather than transferring them.",
                latex_formula=r"\mathrm{H}\cdot + \cdot\mathrm{H} \rightarrow \mathrm{H}:\mathrm{H}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Electrostatic Molecular Binding",
                narration="These shared negative electrons attract both positive nuclei simultaneously, creating a strong electrostatic molecular bond.",
                visual_type="covalent_molecule",
                key_takeaway="Simultaneous attraction of nuclei to shared electrons holds the bond tight.",
                latex_formula=r"F = \frac{k \cdot q_1 q_2}{r^2}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="The Architecture of Molecular Matter",
                narration="Through covalent sharing, essential molecules like water, methane, and DNA build the architecture of our world.",
                visual_type="covalent_summary",
                key_takeaway="Covalent bonds build discrete, robust molecular structures.",
                latex_formula=r"2\mathrm{H}_2 + \mathrm{O}_2 \rightarrow 2\mathrm{H}_2\mathrm{O}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.IONIC_VS_COVALENT: VideoScript(
        topic=SupportedTopic.IONIC_VS_COVALENT,
        title="Ionic vs Covalent Bonding: The Essential Differences",
        overview="Compare electron transfer in ionic crystalline lattices against electron sharing in discrete covalent molecules.",
        scenes=[
            Scene(
                scene_id=1,
                title="Two Paths to Chemical Unity",
                narration="Chemical bonds form either by completely transferring electrons or by sharing them between partner atoms.",
                visual_type="bonding_overview",
                key_takeaway="Atoms bond through either electron transfer (ionic) or electron sharing (covalent).",
                latex_formula=r"\Delta\chi > 2.0 \implies \text{Ionic}, \quad \Delta\chi < 1.7 \implies \text{Covalent}",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Ionic Bonding: Complete Transfer",
                narration="In ionic bonding, metals transfer electrons to nonmetals, forming oppositely charged ions in rigid crystalline lattices.",
                visual_type="ionic_transfer",
                key_takeaway="Metals donate electrons to nonmetals, forming electrostatic ionic lattices.",
                latex_formula=r"\mathrm{Na} + \mathrm{Cl} \rightarrow \mathrm{Na}^+ + \mathrm{Cl}^-",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Covalent Bonding: Mutual Orbital Sharing",
                narration="In covalent bonding, nonmetal atoms share electron pairs between overlapping orbitals to construct discrete molecules.",
                visual_type="covalent_overlap",
                key_takeaway="Covalent bonds involve localized sharing of valence electron pairs.",
                latex_formula=r"\mathrm{H}_2\mathrm{O}, \quad \mathrm{CH}_4, \quad \mathrm{CO}_2",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Physical Properties in Contrast",
                narration="Consequently, ionic salts have very high melting points, while covalent compounds form flexible liquids and gases.",
                visual_type="comparison_table",
                key_takeaway="Ionic compounds are hard, high-melting crystals; covalent substances form diverse molecules.",
                latex_formula=r"T_{\mathrm{melt}}(\mathrm{NaCl}) = 801^{\circ}\mathrm{C} \gg T_{\mathrm{melt}}(\mathrm{H}_2\mathrm{O}) = 0^{\circ}\mathrm{C}",
                duration_target_seconds=8.0,
            ),
        ],
    ),
    SupportedTopic.ATOMIC_STRUCTURE: VideoScript(
        topic=SupportedTopic.ATOMIC_STRUCTURE,
        title="The Structure of the Atom and Subatomic Particles",
        overview="Explore the core architecture of the atom: the central nucleus of protons and neutrons surrounded by quantized electron shells.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Building Blocks of Matter",
                narration="Every element in the cosmos is constructed from tiny atoms composed of three fundamental subatomic particles.",
                visual_type="atomic_intro",
                key_takeaway="Atoms consist of protons, neutrons, and electrons.",
                latex_formula=r"\text{Atom} = p^+ + n^0 + e^-",
                duration_target_seconds=7.0,
            ),
            Scene(
                scene_id=2,
                title="The Dense Central Nucleus",
                narration="At the center lies the dense nucleus of protons and neutrons, holding nearly all atomic mass.",
                visual_type="atomic_nucleus",
                key_takeaway="Protons and neutrons pack the central nucleus with positive charge.",
                latex_formula=r"m_{\text{nucleus}} \approx 99.9\% \cdot m_{\text{atom}}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Quantized Electron Shells",
                narration="Electrons orbit the nucleus in quantized energy shells, accommodating two, eight, or eighteen electrons maximum.",
                visual_type="atomic_shells",
                key_takeaway="Electrons inhabit quantized energy levels with maximum capacity 2n^2.",
                latex_formula=r"N_{\max} = 2n^2 \implies 2, 8, 18, 32",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Valence and Chemical Reactivity",
                narration="Electrons in the outermost valence shell dictate all chemical reactivity and molecular bonding across the universe.",
                visual_type="atomic_summary",
                key_takeaway="Valence electrons govern chemical reactivity and molecular formation.",
                latex_formula=r"\text{Valence Shell} \implies \text{Chemical Behavior}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.EXO_VS_ENDOTHERMIC: VideoScript(
        topic=SupportedTopic.EXO_VS_ENDOTHERMIC,
        title="Exothermic vs Endothermic Reactions: Energy Flows in Chemistry",
        overview="Understand reaction coordinates, activation energy, and whether reactions release heat or absorb energy from their surroundings.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Thermodynamics of Reactions",
                narration="Chemical reactions constantly exchange heat energy with their surroundings, classified as either exothermic or endothermic.",
                visual_type="energy_intro",
                key_takeaway="Chemical reactions either release heat (exothermic) or absorb heat (endothermic).",
                latex_formula=r"\Delta H = H_{\mathrm{products}} - H_{\mathrm{reactants}}",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Exothermic Reactions: Releasing Thermal Energy",
                narration="Exothermic reactions release thermal energy because new bonds in the products are stronger than reactant bonds.",
                visual_type="exothermic_profile",
                key_takeaway="Exothermic: Products have lower energy than reactants; Delta H is negative.",
                latex_formula=r"\Delta H < 0 \quad (\text{Heat Released})",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Endothermic Reactions: Absorbing Heat",
                narration="Endothermic reactions absorb ambient heat from their environment, producing products that store greater chemical enthalpy.",
                visual_type="endothermic_profile",
                key_takeaway="Endothermic: Products have higher energy than reactants; Delta H is positive.",
                latex_formula=r"\Delta H > 0 \quad (\text{Heat Absorbed})",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="The Activation Energy Hill",
                narration="Both reaction types require activation energy to climb the kinetic barrier before transforming into products.",
                visual_type="energy_summary",
                key_takeaway="Activation energy Ea is the kinetic threshold required to initiate reaction.",
                latex_formula=r"k = A \cdot e^{-\frac{E_a}{RT}}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.PERIODIC_TRENDS: VideoScript(
        topic=SupportedTopic.PERIODIC_TRENDS,
        title="How the Periodic Table Organizes Elements and Periodic Trends",
        overview="Explore atomic numbers, periods, groups, and the universal trends of electronegativity and atomic radius across the periodic table.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Map of the Elements",
                narration="The periodic table organizes all chemical elements by atomic number into distinct periods and groups.",
                visual_type="periodic_intro",
                key_takeaway="Elements are organized by atomic number into periods (rows) and groups (columns).",
                latex_formula=r"Z = \text{Number of Protons}",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Electronegativity: The Pull for Electrons",
                narration="Electronegativity, the pull for shared electrons, increases across periods and decreases down each group.",
                visual_type="electronegativity_trend",
                key_takeaway="Electronegativity increases across periods and decreases down groups.",
                latex_formula=r"\chi_{\mathrm{F}} = 3.98 \quad (\text{Most Electronegative})",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Atomic Radius: The Size Gradient",
                narration="Conversely, atomic radius shrinks across periods due to nuclear pull, but expands down groups with new shells.",
                visual_type="atomic_radius_trend",
                key_takeaway="Atomic radius decreases left-to-right and increases top-to-bottom.",
                latex_formula=r"r_{\mathrm{atom}} \propto \frac{n^2}{Z_{\mathrm{eff}}}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Predicting Chemical Reactivity",
                narration="These predictable periodic trends allow chemists to accurately forecast how any element bonds and reacts.",
                visual_type="periodic_summary",
                key_takeaway="Periodic trends provide predictive power for all chemical interactions.",
                latex_formula=r"\text{Position on Table} \implies \text{Reactivity \& Bonding}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.STATES_OF_MATTER: VideoScript(
        topic=SupportedTopic.STATES_OF_MATTER,
        title="States of Matter and Phase Transitions",
        overview="Visualize particle kinetics across solids, liquids, and gases, and how thermal energy drives phase transformations.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Kinetic Nature of Matter",
                narration="Matter exists in three primary physical states: solid, liquid, and gas, governed by molecular kinetic energy.",
                visual_type="matter_intro",
                key_takeaway="Matter exists as solid, liquid, or gas depending on molecular kinetic energy.",
                latex_formula=r"\overline{E_k} = \frac{3}{2} k_B T",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Solid Lattice to Fluid Liquid",
                narration="In solids, particles vibrate in rigid lattices; adding thermal energy melts them into fluid liquids.",
                visual_type="solid_liquid_phase",
                key_takeaway="Adding heat breaks rigid crystal bonds, transitioning solids to liquids.",
                latex_formula=r"\mathrm{Solid} + \Delta H_{\mathrm{fusion}} \rightarrow \mathrm{Liquid}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Vaporization to High-Velocity Gas",
                narration="Further heating vaporizes liquid into high-speed gas particles that move freely and collide chaotically.",
                visual_type="liquid_gas_phase",
                key_takeaway="Vaporization frees molecules into high-speed, chaotic gas collisions.",
                latex_formula=r"\mathrm{Liquid} + \Delta H_{\mathrm{vap}} \rightarrow \mathrm{Gas}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Phase Equilibrium and Conservation",
                narration="Throughout every phase transition, chemical identity is conserved as temperature alters only intermolecular kinetic organization.",
                visual_type="matter_summary",
                key_takeaway="Phase changes alter physical organization while chemical identity remains conserved.",
                latex_formula=r"\mathrm{H}_2\mathrm{O(s)} \rightleftharpoons \mathrm{H}_2\mathrm{O(l)} \rightleftharpoons \mathrm{H}_2\mathrm{O(g)}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.ACID_BASE_NEUTRALIZATION: VideoScript(
        topic=SupportedTopic.ACID_BASE_NEUTRALIZATION,
        title="Acid-Base Neutralization and Titration Reactions",
        overview="Explore what happens when acidic hydronium meets basic hydroxide to form neutral water and salt.",
        scenes=[
            Scene(
                scene_id=1,
                title="When Opposites Meet",
                narration="Acids and bases represent opposite chemical extremes that neutralize one another when mixed in stoichiometric balance.",
                visual_type="neutralization_intro",
                key_takeaway="Neutralization occurs when acids and bases react to cancel each other out.",
                latex_formula=r"\mathrm{Acid} + \mathrm{Base} \rightarrow \mathrm{Salt} + \mathrm{Water}",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="The Fundamental Ionic Reaction",
                narration="At the microscopic level, acidic protons and alkaline hydroxide ions combine rapidly into pure water.",
                visual_type="neutralization_reaction",
                key_takeaway="Hydronium and hydroxide combine directly into water molecules.",
                latex_formula=r"\mathrm{H}^+ + \mathrm{OH}^- \rightarrow \mathrm{H}_2\mathrm{O}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Salt Formation and pH Shift",
                narration="Meanwhile, spectator ions combine to produce dissolved salt as the solution shifts toward neutral pH seven.",
                visual_type="neutralization_indicator",
                key_takeaway="Counter-ions form salt, while solution pH shifts toward neutral 7.",
                latex_formula=r"\mathrm{HCl} + \mathrm{NaOH} \rightarrow \mathrm{NaCl} + \mathrm{H}_2\mathrm{O}",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=4,
                title="Titration and Analytical Precision",
                narration="Chemists employ neutralization reactions during volumetric titrations to determine unknown acid concentrations with high analytical precision.",
                visual_type="neutralization_summary",
                key_takeaway="Titration uses neutralization to accurately calculate chemical concentrations.",
                latex_formula=r"M_1 V_1 = M_2 V_2 \implies \text{Equivalence Point}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
    SupportedTopic.OTHER_STEM: VideoScript(
        topic=SupportedTopic.OTHER_STEM,
        title="Exploring Science: Foundational Principles of Nature",
        overview="An educational exploration of core scientific principles governing physical and molecular interactions.",
        scenes=[
            Scene(
                scene_id=1,
                title="The Framework of Physical Reality",
                narration="Scientific principles provide an empirical framework for deciphering natural systems, modeling the behavior of matter, energy, and fundamental forces across the universe.",
                visual_type="general_intro",
                key_takeaway="Observation and mathematical models describe natural behavior.",
                latex_formula=r"E = mc^2",
                duration_target_seconds=7.5,
            ),
            Scene(
                scene_id=2,
                title="Thermodynamic Laws and Equilibrium",
                narration="Physical systems naturally evolve toward states of minimized free energy and maximum thermodynamic stability, dictating chemical spontaneity and reaction rates.",
                visual_type="general_mechanism",
                key_takeaway="Physical systems minimize potential energy to reach thermodynamic equilibrium.",
                latex_formula=r"\Delta G = \Delta H - T\Delta S < 0",
                duration_target_seconds=8.0,
            ),
            Scene(
                scene_id=3,
                title="Scientific Application and Discovery",
                narration="Understanding these core laws empowers scientists to synthesize novel materials, discover life-saving pharmaceuticals, and engineer advanced technologies for humanity.",
                visual_type="general_summary",
                key_takeaway="Foundational scientific understanding drives innovation and modern technology.",
                latex_formula=r"\vec{F} = m\vec{a}",
                duration_target_seconds=7.5,
            ),
        ],
    ),
}


def get_template_script(topic: SupportedTopic) -> VideoScript:
    """Retrieve the high-fidelity curated script for a topic."""
    return TEMPLATES.get(topic, TEMPLATES[SupportedTopic.OTHER_STEM])
